name: Validate OpenAPI file
on:
  pull_request_target:
    paths:
      - '**.yaml'
    branches:
      - master
    types: [opened, synchronize, edited, reopened]

jobs:
  rate-my-open-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zuplo/rmoa-action@v1
        with:
          filepath: './swagger.yaml'
          apikey: ${{ secrets.RMOA_API_KEY }}
          max-errors: 0
      - name: Rate My Open API
        run: rmoa lint